function [fitresult, gof] = createSolarFit(my_AvgRelHum, my_delT, my_SolRatio)
%CREATEFIT(MY_AVGRELHUM,MY_DELT,MY_SOLRATIO)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: my_AvgRelHum
%      Y Input: my_delT
%      Z Output: my_SolRatio
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Apr-2024 20:30:21


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( my_AvgRelHum, my_delT, my_SolRatio );

% Set up fittype and options.
ft = fittype( 'a*(1-b*H)*(1-exp(-c*(delT)^n))', 'independent', {'H', 'delT'}, 'dependent', 'Rad' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.757740130578333 0.743132468124916 0.392227019534168 0.706046088019609];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'my_SolRatio vs. my_AvgRelHum, my_delT', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'my_AvgRelHum', 'Interpreter', 'none' );
ylabel( 'my_delT', 'Interpreter', 'none' );
zlabel( 'my_SolRatio', 'Interpreter', 'none' );
grid on
view( -58.2, 18.9 );

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, [xData, yData], zData, 'Style', 'Residual' );
legend( h, 'untitled fit 1 - residuals', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'my_AvgRelHum', 'Interpreter', 'none' );
ylabel( 'my_delT', 'Interpreter', 'none' );
zlabel( 'my_SolRatio', 'Interpreter', 'none' );
grid on
view( -58.2, 18.9 );


