function DavisDaily = ImportData(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DAVISDAILY = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DAVISDAILY = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DAVISDAILY = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DavisDaily = importfile("/MATLAB Drive/Script_Solar/DavisDaily.xlsx", "DavisDaily", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Apr-2024 20:01:50

%% Input handling

% If no sheet is specified, read from DavisDaily
if nargin == 1 || isempty(sheetName)
    sheetName = "DavisDaily";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 15);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["StnId", "Station", "Region", "Date", "DayofYear", "CIMISEto", "Precip", "SolRatio", "AvgVap", "MaxAirTemp", "MinAirTemp", "AvgAirTemp", "MaxRelHum", "MinRelHum", "AvgRelHum"];
opts.SelectedVariableNames = ["Date", "DayofYear", "SolRatio", "MaxAirTemp", "MinAirTemp", "AvgRelHum"];
opts.VariableTypes = ["char", "char", "char", "datetime", "double", "char", "char", "double", "char", "double", "double", "char", "char", "char", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, ["StnId", "Station", "Region", "CIMISEto", "Precip", "AvgVap", "AvgAirTemp", "MaxRelHum", "MinRelHum"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["StnId", "Station", "Region", "CIMISEto", "Precip", "AvgVap", "AvgAirTemp", "MaxRelHum", "MinRelHum"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["DayofYear", "SolRatio", "MaxAirTemp", "MinAirTemp", "AvgRelHum"], "TreatAsMissing", '');

% Import the data
DavisDaily = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    DavisDaily = [DavisDaily; tb]; %#ok<AGROW>
end

end